### ISSUE TITLE
Reflecting validation errors in the tree view

### ISSUE THREAD

**Issue by franciscorubin** [FelixThieleTUM/JsonFormsEditor#11]
The tree element could be colored red if there is any error.
This would help the user to find the error, so he doesn't have to look into each property window looking for it.

**Comment by franciscorubin** [comment]
First identify which errors can occur.

**Comment by franciscorubin** [comment]
Validate data schema when it's uploaded

**Comment by JonasHelming** [comment]
To make sure, that we are on the same page: We want to validate the UI Schema, against the UI Meta Schema, right? The data schema only relevant to check whether the "scope" of controls is valid.

**Comment by edgarmueller** [comment]
Yes, we are on the same page, nevertheless both  scenarios are possible. Additionally, I don't think the tooling currently allows to create invalid UI schemas. Testing this could involve a custom layout which expects at least 2 children or something the like.

**Comment by JonasHelming** [comment]
Having an empty or undefined scope would be one, right?

**Comment by edgarmueller** [comment]
As well, yes, but this would need to be set programatically since `scope` is read-only in the UI.

**Comment by edgarmueller** [comment]
Initial validation has been implemented, some fine tuning might be necessary for which we'll create follow-up items.
