### ISSUE TITLE
Provide tooling support for visibility rules

### ISSUE THREAD

**Issue by JonasHelming** [FelixThieleTUM/JsonFormsEditor#23]
see https://github.com/eclipsesource/jsonforms/issues/172
@eneufeld  knows the details

**Comment by JonasHelming** [comment]
First present a cocnept o how the support could look like

**Comment by edgarmueller** [comment]
The [UI Meta schema](https://gist.github.com/edgarmueller/6ba6d6dd7b88bad03569) has been updated accordingly to support rules. For now, it only contains the definition of a single visibility rule and its definition might change, but it should be enough to start working on the implementation within the editor.

**Comment by edgarmueller** [comment]
I'll close this for now since initial support for rules has been implemented, but it's likely that we are gonna need to tweak the UI some more. I'll create follow up issues then.
