### ISSUE TITLE
Validation triggers

### ISSUE THREAD

**Issue by edgarmueller** [FelixThieleTUM/JsonFormsEditor#42]
Validation, is not triggered when editing rules, which must be the case.

**Comment by edgarmueller** [comment]
This might be related to JSON Forms (Notifications wise).

**Comment by hecforga** [comment]
@edgarmueller I'm having some problems understanding how "allOf" and "additionalProperties" fit together. I get some unexpected validation errors when editing the rules if addtionalProperties is set to false. We can look at this together in the office.
