### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by JonasHelming** [FelixThieleTUM/JsonFormsEditor#52]
Create a control, a categorization, a category and then move the control into the category.
A non descipritve and unresolvable validation error appears: 
No enum match for: "Categorization"
Data does not match any schemas from "anyOf"
Additional properties not allowed
Missing required property: scope

**Comment by edgarmueller** [comment]
This happend due to the meta schema, which has been too strict, since we introduced the idea of runtime properties in the UI schema. The current, updated draft (without the `additionalProperties: false` constraint) can be found [here](https://gist.github.com/edgarmueller/6ba6d6dd7b88bad03569).
