### ISSUE TITLE
Selecting Schema from URL not working

### ISSUE THREAD

**Issue by eneufeld** [FelixThieleTUM/JsonFormsEditor#56]
I tried selecting a schema using this URL: 
[https://raw.githubusercontent.com/eneufeld/angular2-gedcomx-app/master/gedcomx.schema.json](url)
After I press ok the dialog closes but nothing happens. so I don't have a model.

**Comment by hecforga** [comment]
Fixed. You can check it at: http://jsonformseditor.herokuapp.com
