### ISSUE TITLE
Multiple DnD/Multi-edit support

### ISSUE THREAD

**Issue by franciscorubin** [FelixThieleTUM/JsonFormsEditor#8]
Being able to drag multiple elements from the toolbox to the tree would speed up edition process

The extra elements could be selected by ctrl+clicking them and using the keyboard with ctrl+up/down

**Comment by franciscorubin** [comment]
Implementing this would involve angular-ui-tree modifications, which might take a lot of time

**Comment by hecforga** [comment]
We can achieve addition of multiple elements from the toolbox to the tree in other different ways than Drag&Drop. For example:
- An action button inside the tree element "Generate controls" or "Insert controls" that shows a dialog in which the user can select multiple controls to be added.
- A button in the toolbox "Select all" that selects all controls in that hierarchy level. Then the user clicks on the desired tree element and the controls are inserted. The user can also deselect or reselect some controls in the toolbox.

What do you think about these alternative approaches? Do you have more ideas? @JonasHelming

**Comment by franciscorubin** [comment]
I forked the angular-ui-tree repo and made changes to allow multiple drag&drop.
(https://github.com/pancho111203/angular-ui-tree)

You can specify which key will be used for selecting elements. It is currently set up with control.
